name: Docker Build

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v7
      - uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: int128/kaniko-action@v1
        with:
          push: true
          tags: |
            ghcr.io/justsomebody42/color-combos-carousel:latest
            ghcr.io/justsomebody42/color-combos-carousel:${{ github.sha }}
